# Semantic Release Configuration for Agenterra
# Uses cargo-release for automated semantic versioning

# Synchronize workspace crate versions
consolidate-commits = true
shared-version = true

# Commit and tag configuration
pre-release-commit-message = "chore: release {{version}}"
tag-message = "chore: release {{version}}"
tag-name = "v{{version}}"
tag-prefix = "v"

# Push configuration
push = true
push-remote = "origin"

# Release workflow
pre-release-replacements = [
  { file = "../../README.md", search = "agenterra@\\d+\\.\\d+\\.\\d+", replace = "agenterra@{{version}}" },
  { file = "../../CLAUDE.md", search = "v\\d+\\.\\d+\\.\\d+", replace = "v{{version}}" }
]

# Skip features for automated releases
verify = true
sign-commit = false
sign-tag = false
publish = false  # Don't publish to crates.io automatically

# Pre-release hooks
pre-release-hook = ["cargo", "test", "--all"]