[workspace]
changelog_update = true
git_release_enable = true
features_always_increment_minor = false
release_always = false
publish = true
git_tag_name = "agenterra-v{{ version }}"

[[package]]
name = "agenterra"
release = true
publish = true
