[workspace]
changelog_update = true
git_release_enable = true
features_always_increment_minor = false
publish = false

# Per-package overrides (optional)
[[package]]
name = "agenterra"
release = false

[[package]]
name = "agenterra-core"
release = false
