# Rustfmt configuration for Agenterra
# Ensures consistent formatting across the project

edition = "2024"
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"
indent_style = "Block"
wrap_comments = true
format_code_in_doc_comments = true
normalize_comments = true
normalize_doc_attributes = true

# Function formatting
fn_single_line = false
where_single_line = false

# Import formatting
imports_layout = "Vertical"
group_imports = "StdExternalCrate"

# Misc formatting preferences
trailing_comma = "Vertical"
trailing_semicolon = true
use_field_init_shorthand = true
force_explicit_abi = true