name: Release-plz PR Update
run-name: "🚀 Release-plz PR Update (main)"

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
    branches: [main]

permissions:
  contents: write     # commit changelog & Cargo.toml bumps
  pull-requests: write
  id-token: write

env:
  CARGO_TERM_COLOR: always

jobs:
  release-plz-pr:
    name: Release-plz PR
    # Only run if CI workflow succeeded and not from release-plz bot
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.actor.login != 'release-plz[bot]'
    runs-on: ubuntu-latest
    concurrency:
      group: release-plz-pr
      cancel-in-progress: true
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ runner.os }}-release-${{ hashFiles('**/Cargo.lock') }}
          cache-on-failure: true

      - name: Run release-plz (PR)
        uses: release-plz/action@v0.5.107
        with:
          command: release-pr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
